#pragma once
// AI: below section was generated by an AI
/*
 * Nanoleaf Shapes layout string -> panel positions -> 2D grid (for an automatic ledmap).
 * Plain C++ without Arduino dependencies, so it can be tested on a host.
 *
 * Grammar and geometry: LeafBus PROTOCOL.md sections 7.2 and 7.6. Positions are in mm, y up,
 * panel 0 (the one the controller is plugged into) at the origin with orientation 0.
 */
#include <stdint.h>
#include <stddef.h>
#include <math.h>

namespace leafbus {

enum Shape : uint8_t { SHAPE_UNKNOWN, SHAPE_MINI_TRIANGLE, SHAPE_TRIANGLE, SHAPE_HEXAGON };

struct Panel {
  uint8_t node;        // node byte from the layout string
  uint8_t connectors;
  uint8_t root;        // connector facing the controller
  uint8_t shape;
  int16_t parent;      // layout position of the parent, -1 for panel 0
  int8_t  parentConn;  // parent connector this panel hangs on
  float   x, y, o;     // centre in mm and orientation in degrees
};

constexpr int     MAX_GRID     = 255;    // WLED limits matrix width and height to 255
constexpr int     MAX_PANELS   = 64;
constexpr uint8_t PSU_CODE     = 1;      // connector-count code of the power supply node
constexpr float   MIN_STEP_MM  = 1.0f;   // centres closer than this count as the same row/column
// Every Shapes panel has a 67 mm side, so every centre (mini triangle, triangle, hexagon) lies on a lattice of
// side/4 by side/(2*sqrt(3)) for layout rotations in steps of 60 degrees. Mapping to it keeps neighbours evenly
// spaced: horizontal neighbours are always two columns apart.
constexpr float   LATTICE_X    = 16.75f;
constexpr float   LATTICE_Y    = 19.341344f;
constexpr float   LATTICE_TOL  = 0.1f;    // cells; beyond this the rotation broke the lattice

namespace detail {

struct Parser {
  const uint8_t *s;
  size_t len, pos;
  Panel *out;
  int count, max;
  bool err;
};

inline int connectorCount(int code) { return code == 0 ? 8 : code == PSU_CODE ? 0 : code == 7 ? 9 : code; }

// The first separators of a node carry the panel subtype (PROTOCOL.md 7.3)
inline uint8_t shapeOf(int connectors, const uint8_t *sep, int nsep) {
  if (connectors == 3 && nsep >= 1 && ((sep[0] >> 2) & 7) <= 1) return SHAPE_MINI_TRIANGLE;
  if (connectors == 6 && nsep >= 2) {
    if ((sep[1] & 7) == 1) return SHAPE_HEXAGON;
    if ((sep[1] & 7) == 2) return SHAPE_TRIANGLE;
  }
  return SHAPE_UNKNOWN;
}

// Walk the node's connectors in a circle from root + 1; a separator whose next connector would be
// the root belongs to the parent (PROTOCOL.md 7.2)
inline void parseNode(Parser &p, int parent, int parentConn) {
  uint8_t b = p.s[p.pos++];
  int code = (b >> 4) & 7, root = b & 7, n = connectorCount(code);
  if (code == PSU_CODE) return;
  if (p.count >= p.max || root >= n) { p.err = true; return; }
  int idx = p.count++;
  Panel &panel = p.out[idx];
  panel = Panel{b, (uint8_t)n, (uint8_t)root, SHAPE_UNKNOWN, (int16_t)parent, (int8_t)parentConn, 0, 0, 0};
  uint8_t sep[2] = {0, 0};
  int nsep = 0, e = (root + 1) % n;
  while (p.pos < p.len && !p.err) {
    uint8_t c = p.s[p.pos];
    if (c & 0x80) {
      parseNode(p, idx, e);
      continue;
    }
    int next = (e + 1) % n;
    if (next == root) break;
    if (nsep < 2) sep[nsep] = c;
    nsep++;
    e = next;
    p.pos++;
  }
  p.out[idx].shape = shapeOf(n, sep, nsep < 2 ? nsep : 2);
}

inline void rotate(float x, float y, float deg, float &rx, float &ry) {
  float r = deg * (float)M_PI / 180.0f, c = cosf(r), s = sinf(r);
  rx = c * x - s * y;
  ry = s * x + c * y;
}

// Angle of the side that carries connector e, and the vector from the centre to connector e
inline float sideAngle(uint8_t shape, int e) {
  switch (shape) {
    case SHAPE_MINI_TRIANGLE: return 120.0f * e;
    case SHAPE_TRIANGLE:      return 120.0f * (((e + 1) >> 1) % 3);
    default:                  return 60.0f * e; // SHAPE_HEXAGON
  }
}

inline void connectorVector(uint8_t shape, int e, float &x, float &y) {
  float bx = 0.0f, by;
  switch (shape) {
    case SHAPE_MINI_TRIANGLE: by = -19.341344f; break;                        // inradius of a 67 mm triangle
    case SHAPE_TRIANGLE:      bx = (e % 2 == 0) ? -33.5f : 33.5f; by = -38.682688f; break; // two connectors per 134 mm side
    default:                  by = -58.023702f; break;                        // hexagon apothem
  }
  rotate(bx, by, -sideAngle(shape, e), x, y);
}

} // namespace detail

// Parse a layout string (without the 0x40 terminator) into panels in layout order.
// Returns the number of panels, or -1 if the string does not follow the grammar.
inline int parseLayout(const uint8_t *s, size_t len, Panel *out, int maxPanels) {
  detail::Parser p{s, len, 0, out, 0, maxPanels, false};
  if (len == 0 || !(s[0] & 0x80)) return -1;
  detail::parseNode(p, -1, -1);
  return (p.err || p.pos != len) ? -1 : p.count;
}

// Place every panel (PROTOCOL.md 7.6). Parents always come before their children in layout order.
inline bool placePanels(Panel *p, int n) {
  for (int i = 0; i < n; i++) {
    if (p[i].shape == SHAPE_UNKNOWN) return false;
    if (p[i].parent < 0) {
      p[i].x = p[i].y = p[i].o = 0.0f;
      continue;
    }
    const Panel &par = p[p[i].parent];
    int pe = p[i].parentConn, ce = p[i].root;
    float o = fmodf(par.o + 180.0f + detail::sideAngle(p[i].shape, ce) - detail::sideAngle(par.shape, pe), 360.0f);
    if (o < 0.0f) o += 360.0f;
    float vpx, vpy, vcx, vcy, rcx, rcy, dx, dy;
    detail::connectorVector(par.shape, pe, vpx, vpy);
    detail::connectorVector(p[i].shape, ce, vcx, vcy);
    detail::rotate(vcx, vcy, o - par.o, rcx, rcy);
    detail::rotate(vpx - rcx, vpy - rcy, par.o, dx, dy);
    p[i].o = o;
    p[i].x = par.x + dx;
    p[i].y = par.y + dy;
  }
  return true;
}

// Assign each panel its own grid cell after rotating the layout by rotationDeg (counter-clockwise): the panel
// lattice for multiples of 60 degrees, otherwise a grid of square cells.
// Row 0 is the top. cells[i] = row * width + column for panel i. Returns false if no grid of at most
// 255 x 255 separates every panel.
inline bool gridPanels(const Panel *p, int n, float rotationDeg, uint8_t &width, uint8_t &height, uint16_t *cells) {
  if (n <= 0) return false;
  float xs[MAX_PANELS], ys[MAX_PANELS];
  if (n > MAX_PANELS) return false;
  float minX = 1e9f, maxX = -1e9f, minY = 1e9f, maxY = -1e9f, step = 1e9f;
  for (int i = 0; i < n; i++) {
    detail::rotate(p[i].x, p[i].y, rotationDeg, xs[i], ys[i]);
    minX = fminf(minX, xs[i]); maxX = fmaxf(maxX, xs[i]);
    minY = fminf(minY, ys[i]); maxY = fmaxf(maxY, ys[i]);
  }
  // lattice grid: exact, evenly spaced
  bool onLattice = true;
  for (int i = 0; i < n && onLattice; i++) {
    float fx = (xs[i] - minX) / LATTICE_X, fy = (maxY - ys[i]) / LATTICE_Y;
    onLattice = fabsf(fx - roundf(fx)) <= LATTICE_TOL && fabsf(fy - roundf(fy)) <= LATTICE_TOL;
  }
  if (onLattice) {
    int w = (int)lroundf((maxX - minX) / LATTICE_X) + 1, h = (int)lroundf((maxY - minY) / LATTICE_Y) + 1;
    bool clash = w > MAX_GRID || h > MAX_GRID;
    for (int i = 0; i < n && !clash; i++) {
      int col = (int)lroundf((xs[i] - minX) / LATTICE_X), row = (int)lroundf((maxY - ys[i]) / LATTICE_Y);
      cells[i] = (uint16_t)(row * w + col);
      for (int j = 0; j < i; j++) if (cells[j] == cells[i]) { clash = true; break; }
    }
    if (!clash) {
      width = (uint8_t)w;
      height = (uint8_t)h;
      return true;
    }
  }

  // other rotations: square cells, the smallest spacing between distinct rows or columns keeps panels apart
  for (int i = 0; i < n; i++) for (int j = i + 1; j < n; j++) {
    float dx = fabsf(xs[i] - xs[j]), dy = fabsf(ys[i] - ys[j]);
    if (dx >= MIN_STEP_MM) step = fminf(step, dx);
    if (dy >= MIN_STEP_MM) step = fminf(step, dy);
  }
  if (n == 1 || step > 1e8f) step = 1.0f;
  step = fmaxf(step, fmaxf(maxX - minX, maxY - minY) / (MAX_GRID - 1));

  for (int attempt = 0; attempt < 8; attempt++, step *= 0.75f) {
    int w = (int)lroundf((maxX - minX) / step) + 1, h = (int)lroundf((maxY - minY) / step) + 1;
    if (w > MAX_GRID || h > MAX_GRID) return false;
    bool clash = false;
    for (int i = 0; i < n && !clash; i++) {
      int col = (int)lroundf((xs[i] - minX) / step), row = (int)lroundf((maxY - ys[i]) / step);
      cells[i] = (uint16_t)(row * w + col);
      for (int j = 0; j < i; j++) if (cells[j] == cells[i]) { clash = true; break; }
    }
    if (!clash) {
      width = (uint8_t)w;
      height = (uint8_t)h;
      return true;
    }
  }
  return false;
}

} // namespace leafbus
// AI: end
